services:
  - type: web
    name: api-cuentas-nestjs
    # ¡Cambiamos a Docker!
    env: docker
    plan: free
    healthCheckPath: /api/health
    # Docker se encarga de los comandos, así que buildCommand y startCommand se eliminan.
    envVars:
      - key: NODE_ENV
        value: production
      # Agrega aquí tus otras variables de entorno
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: tu-base-de-datos-en-render # Reemplaza con el nombre de tu DB
      #     property: connectionString
      # - key: JWT_SECRET
      #   sync: false
