services:
  - type: web
    name: api-cuentas-nestjs
    env: node
    plan: free
    buildCommand: chmod +x scripts/render-build.sh && scripts/render-build.sh
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5051
    healthCheckPath: /api/health
